CREATE TABLE IF NOT EXISTS usr (
   id BIGSERIAL PRIMARY KEY,
  name VARCHAR(25) NOT NULL,
  email VARCHAR(25) NOT NULL,
  login VARCHAR(25) NOT NULL,
  password VARCHAR(255) NOT NULL,
  enable BOOLEAN NOT NULL,
  role VARCHAR(20) NOT NULL
);