CREATE TABLE IF NOT EXISTS tasks (
  id BIGSERIAL ,
  name VARCHAR(20) NOT NULL,
  creationDate DATE DEFAULT CURRENT_DATE,
  developerId BIGSERIAL,
  status VARCHAR(20) NOT NULL,
  CONSTRAINT tasks_id primary key (id)
);

ALTER TABLE tasks
ADD CONSTRAINT TASKS_DEVELOPER_ID_FK
FOREIGN KEY (developerId) REFERENCES usr (id);
