CREATE TABLE IF NOT EXISTS tasks (
   id BIGSERIAL PRIMARY KEY ,
  name VARCHAR(20) NOT NULL,
  creation_date DATE DEFAULT CURRENT_DATE,
  developer_id BIGSERIAL,
  status VARCHAR(20) NOT NULL
);

ALTER TABLE tasks
ADD CONSTRAINT TASKS_DEVELOPER_ID_FK
FOREIGN KEY (developer_id) REFERENCES usr (id);
